#!/usr/bin/python3
"""Class that inherits from list"""

class MyList(list):
"""method to sort the list"""

    def print_sorted(self):
        """sorted list printed"""
        sorted_list = sorted(self)
        print(sorted_list)
